version: '3'
services:
  nginx:
    image: gateway_nginx
    container_name: nginx_service
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.bookworm.dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVICE_NAME="nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_CONFIG_DIR:-./config/nginx}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_CONFIG_DIR:-./config/nginx}/sites-available:/etc/nginx/sites-available:ro
      - ${NGINX_CONFIG_DIR:-./config/nginx}/sites-enabled:/etc/nginx/sites-enabled:ro
